import { Check, Plus, Trash2, X } from 'lucide-react';
import { useState } from 'react';
import type { ViewProps } from '../App';
import { formatCents, splitExpense } from '../lib/money';

export default function ExpensesView({ state, actions }: ViewProps) {
  const [open, setOpen] = useState(false); const [title, setTitle] = useState(''); const [amount, setAmount] = useState(''); const [payerId, setPayerId] = useState(state.members[0].id); const [category, setCategory] = useState('日用品');
  const total = state.expenses.reduce((s, e) => s + e.amountCents, 0); const outstanding = state.expenses.filter(e => !e.settled).reduce((s, e) => s + e.amountCents, 0);
  const submit = (e: React.FormEvent) => { e.preventDefault(); const cents = Math.round(Number(amount) * 100); if (!title.trim() || !cents) return; actions.addExpense({ id: crypto.randomUUID(), title: title.trim(), category, amountCents: cents, payerId, participantIds: state.members.map(m => m.id), date: '刚刚', settled: false }); setTitle(''); setAmount(''); setOpen(false); };
  return <div className="view-stack"><div className="page-heading"><div><p className="eyebrow">02 / 05 · MONEY</p><h1>费用 AA</h1><p className="lede">每一笔公共支出都留有记录，结算时不用再翻聊天记录。</p></div><button className="primary-button" onClick={() => setOpen(true)}><Plus size={16} />记录支出</button></div><div className="summary-row"><div><span>本月总支出</span><strong>{formatCents(total)}</strong></div><div><span>待结清</span><strong className="accent-text">{formatCents(outstanding)}</strong></div><div><span>参与室友</span><strong>{state.members.length}<small> 人</small></strong></div></div>{open && <form className="inline-form" onSubmit={submit}><div className="form-top"><strong>新增公共支出</strong><button type="button" className="icon-button" onClick={() => setOpen(false)}><X size={16} /></button></div><label>事项<input value={title} onChange={e => setTitle(e.target.value)} placeholder="例如：网费" /></label><label>金额（元）<input type="number" min="0" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} placeholder="0.00" /></label><label>付款人<select value={payerId} onChange={e => setPayerId(e.target.value)}>{state.members.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>分类<select value={category} onChange={e => setCategory(e.target.value)}><option>日用品</option><option>水电</option><option>房租</option><option>其他</option></select></label><button className="primary-button" type="submit">保存支出</button></form>}<div className="panel table-panel"><div className="panel-heading"><div><p className="eyebrow">EXPENSE LOG</p><h2>支出明细</h2></div><span className="panel-count">{state.expenses.length} 笔</span></div><div className="expense-list">{state.expenses.map(item => { const payer = state.members.find(m => m.id === item.payerId); const each = splitExpense(item.amountCents, item.participantIds)[state.members[0].id] ?? 0; return <div className="expense-row" key={item.id}><div className="expense-date">{item.date}</div><div className="expense-main"><strong>{item.title}</strong><span>{item.category} · {payer?.name} 先付</span></div><div className="expense-share"><span>人均</span><strong>{formatCents(each)}</strong></div><div className="expense-amount">{formatCents(item.amountCents)}</div><button className={item.settled ? 'status-button settled' : 'status-button'} onClick={() => actions.toggleExpense(item.id)}>{item.settled ? <><Check size={14} />已结清</> : '待结清'}</button><button className="icon-button danger" onClick={() => actions.removeExpense(item.id)} aria-label="删除支出"><Trash2 size={15} /></button></div>})}</div></div></div>;
}
