import { ArrowUpRight, Check, CircleDollarSign, Clock3, PackageOpen, Plus, WalletCards } from 'lucide-react';
import type { HouseholdState } from '../types';
import { formatCents, splitExpense } from '../lib/money';
import type { View } from '../App';

export default function OverviewView({ state, onNavigate }: { state: HouseholdState; onNavigate: (view: View) => void }) {
  const total = state.expenses.reduce((sum, item) => sum + item.amountCents, 0);
  const unsettled = state.expenses.filter(item => !item.settled);
  const me = state.members[0];
  const owed = state.expenses.reduce((sum, item) => sum + (item.participantIds.includes(me.id) ? (splitExpense(item.amountCents, item.participantIds)[me.id] ?? 0) : 0), 0);
  const paid = state.expenses.filter(item => item.payerId === me.id).reduce((sum, item) => sum + item.amountCents, 0);
  const today = state.chores.find(item => item.due === '今天' && !item.completed);
  const low = state.supplies.filter(item => item.quantity <= item.minimum);
  return <div className="view-stack">
    <section className="hero-row"><div><p className="eyebrow">{state.month} / 房屋状态</p><h1>一起住，账要清楚。</h1><p className="lede">把房租、水电、值日和日常补给放在同一个地方，少一点猜测，多一点默契。</p></div><div className="hero-index">01<span>/ 05</span></div></section>
    <section className="stat-grid"><button className="stat-card stat-card-main" onClick={() => onNavigate('expenses')}><div className="stat-head"><span>本月公共支出</span><CircleDollarSign size={18} /></div><strong>{formatCents(total)}</strong><span className="stat-note">{state.expenses.length} 笔记录 <ArrowUpRight size={14} /></span></button><div className="stat-card"><div className="stat-head"><span>我的应付</span><WalletCards size={18} /></div><strong>{formatCents(owed)}</strong><span className="stat-note muted">已付 {formatCents(paid)}</span></div><button className="stat-card" onClick={() => onNavigate('chores')}><div className="stat-head"><span>待完成值日</span><Clock3 size={18} /></div><strong>{state.chores.filter(item => !item.completed).length}<small> 项</small></strong><span className="stat-note">{today ? `今天 · ${today.title}` : '今天没有待办'} <ArrowUpRight size={14} /></span></button><button className="stat-card" onClick={() => onNavigate('supplies')}><div className="stat-head"><span>需要补货</span><PackageOpen size={18} /></div><strong>{low.length}<small> 件</small></strong><span className="stat-note">{low[0]?.name ?? '库存充足'} <ArrowUpRight size={14} /></span></button></section>
    <section className="overview-grid"><div className="panel status-panel"><div className="panel-heading"><div><p className="eyebrow">NEXT ACTIONS</p><h2>房屋状态轨</h2></div><span className="panel-count">{unsettled.length + (today ? 1 : 0) + low.length} 件待处理</span></div><div className="status-rail"><button className="rail-item" onClick={() => onNavigate('expenses')}><span className="rail-dot accent" /><div><strong>{unsettled.length ? `${unsettled.length} 笔费用待结清` : '费用已结清'}</strong><span>{unsettled[0] ? `${unsettled[0].title} · ${formatCents(unsettled[0].amountCents)}` : '本月没有待处理账单'}</span></div><ArrowUpRight size={16} /></button><button className="rail-item" onClick={() => onNavigate('chores')}><span className="rail-dot dark" /><div><strong>{today ? `今天由 ${state.members.find(m => m.id === today.assigneeId)?.name} 值日` : '今日值日已完成'}</strong><span>{today?.title ?? '可以看看本周的值日安排'}</span></div><ArrowUpRight size={16} /></button><button className="rail-item" onClick={() => onNavigate('supplies')}><span className="rail-dot gold" /><div><strong>{low.length ? `${low.length} 件物品低于库存线` : '公共物品库存充足'}</strong><span>{low[0] ? `${low[0].name} 还剩 ${low[0].quantity}${low[0].unit}` : '暂时不需要采购'}</span></div><ArrowUpRight size={16} /></button></div></div><div className="panel activity-panel"><div className="panel-heading"><div><p className="eyebrow">RECENT</p><h2>最近动态</h2></div><button className="text-button" onClick={() => onNavigate('expenses')}>查看全部</button></div><div className="activity-list">{state.activity.slice(0, 4).map(item => <div className="activity-item" key={item.id}><span className={`activity-dot ${item.tone}`} /><div><strong>{item.text}</strong><span>{item.time}</span></div></div>)}</div><button className="quick-add" onClick={() => onNavigate('expenses')}><Plus size={16} />记录一笔公共支出</button></div></section>
    <section className="rule-strip"><Check size={16} /><span>本月公约确认进度</span><strong>{state.rules.filter(rule => rule.acknowledgedBy.length === state.members.length).length}/{state.rules.length}</strong><button onClick={() => onNavigate('rules')}>去查看 <ArrowUpRight size={14} /></button></section>
  </div>;
}
